[profile.default]
src = "ethereum"
out = "out"
libs = ["node_modules", "lib"]
solc = "0.8.30"
optimizer = true
optimizer_runs = 200
via_ir = false
evm_version = "prague"
gas_reports = ["*"]
verbosity = 3

[profile.ci]
fuzz = { runs = 256 }
invariant = { runs = 256 }

[remappings]
forge-std = "lib/forge-std/src"
"@openzeppelin/" = "node_modules/@openzeppelin/"
"@layerzerolabs/" = "node_modules/@layerzerolabs/"
